import {
  User,
  Link2,
  Image as ImageIcon,
  Globe,
  TrendingUp,
  Type,
  MapPin,
  Music,
} from "lucide-react";
import type { BentoBlockType, BlockData } from "@/types/editor";

export const BENTO_BLOCK_TYPES: BentoBlockType[] = [
  {
    type: "profile",
    icon: User,
    label: "Profile",
    desc: "Main identity card",
    color: "text-blue-500",
    bg: "bg-blue-500/10 border-blue-500/20",
    glowColor: "#3b82f6",
    defaultColSpan: 1,
    defaultRowSpan: 1,
  },
  {
    type: "link",
    icon: Link2,
    label: "Custom Link",
    desc: "External URL",
    color: "text-emerald-500",
    bg: "bg-emerald-500/10 border-emerald-500/20",
    glowColor: "#10b981",
    defaultColSpan: 1,
    defaultRowSpan: 1,
  },
  {
    type: "image",
    icon: ImageIcon,
    label: "Image",
    desc: "Visual content",
    color: "text-purple-500",
    bg: "bg-purple-500/10 border-purple-500/20",
    glowColor: "#a855f7",
    defaultColSpan: 1,
    defaultRowSpan: 1,
  },
  {
    type: "social",
    icon: Globe,
    label: "Social",
    desc: "Network profile",
    color: "text-pink-500",
    bg: "bg-pink-500/10 border-pink-500/20",
    glowColor: "#ec4899",
    defaultColSpan: 1,
    defaultRowSpan: 1,
  },
  {
    type: "stats",
    icon: TrendingUp,
    label: "Stats",
    desc: "Numbers & metrics",
    color: "text-amber-500",
    bg: "bg-amber-500/10 border-amber-500/20",
    glowColor: "#f59e0b",
    defaultColSpan: 1,
    defaultRowSpan: 1,
  },
  {
    type: "text",
    icon: Type,
    label: "Text",
    desc: "Bio or quotes",
    color: "text-slate-500",
    bg: "bg-slate-500/10 border-slate-500/20",
    glowColor: "#64748b",
    defaultColSpan: 1,
    defaultRowSpan: 1,
  },
  {
    type: "location",
    icon: MapPin,
    label: "Location",
    desc: "3D Interactive Globe",
    color: "text-teal-500",
    bg: "bg-teal-500/10 border-teal-500/20",
    glowColor: "#14b8a6",
    defaultColSpan: 1,
    defaultRowSpan: 1,
  },
  {
    type: "music",
    icon: Music,
    label: "Spotify",
    desc: "Real embedded player",
    color: "text-green-500",
    bg: "bg-green-500/10 border-green-500/20",
    glowColor: "#22c55e",
    defaultColSpan: 2,
    defaultRowSpan: 1,
  },
];

export const BENTO_DEFAULTS: Record<string, BlockData> = {
  profile: { title: "New Profile", bio: "Bio here" },
  link: { label: "New Link", url: "https://", icon: "link" },
  social: { platform: "github", url: "https://" },
  image: { image_url: "" },
  stats: { title: "50+", label: "Projects Done" },
  text: { title: "About Me", bio: "Building products that matter." },
  location: { label: "October Gardens, Giza", lat: 29.95, lng: 31.0 },
  music: { url: "https://open.spotify.com/track/7MXVkk9YMqqcbI1ENIli1F" },
};
